"""
Export configuration management (``ddd_export.yaml``).

The YAML file lists every available (source, field) combination with a
boolean toggle controlling whether that field is included in exports.
Running ``init_export_yaml`` is always safe: it adds newly discovered
fields with a default of ``true`` while preserving any existing toggles.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

import yaml

#: Default path for the export configuration file.
DEFAULT_YAML_PATH = Path("ddd_export.yaml")

_YAML_HEADER = """\
# ddd_export.yaml — field export configuration
# Generated by `ddd export init`.
#
# Set a field to true to include it in exports, false to exclude it.
# Re-run `ddd export init` at any time to pick up newly ingested fields
# without losing your existing toggle settings.

"""


def init_export_yaml(
    con: sqlite3.Connection,
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> tuple[dict[str, dict[str, bool]], int, int]:
    """
    Create or update *yaml_path* with all (source, field) combinations.

    * Existing toggles are preserved unchanged.
    * Newly discovered fields are added with ``true`` (included by default).
    * Sources or fields that no longer exist in the DB are dropped.

    Parameters
    ----------
    con:
        Open database connection.
    yaml_path:
        Path to write the YAML file. Defaults to ``ddd_export.yaml`` in
        the current working directory.

    Returns
    -------
    tuple
        ``(config, n_added, n_total)`` — the final config dict, the number
        of new field entries added, and the total number of field entries.
    """
    # Load existing config, preserving user-edited toggles.
    existing: dict[str, Any] = {}
    if yaml_path.exists():
        with yaml_path.open(encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh)
            if isinstance(loaded, dict):
                existing = loaded

    # All (source, field) currently in the DB.
    db_rows = con.execute("SELECT source, field FROM fields ORDER BY source, field").fetchall()
    db_sources: set[str] = {row["source"] for row in db_rows}

    # Seed config from existing file, but only for sources still in the DB.
    config: dict[str, dict[str, bool]] = {}
    for source, fields in existing.items():
        if source in db_sources and isinstance(fields, dict):
            config[source] = {k: bool(v) for k, v in fields.items()}

    # Add any new (source, field) pairs from the DB.
    n_added = 0
    for row in db_rows:
        source, field = row["source"], row["field"]
        if source not in config:
            config[source] = {}
        if field not in config[source]:
            config[source][field] = True
            n_added += 1

    n_total = sum(len(fields) for fields in config.values())

    # Write the file: header comment + YAML body.
    with yaml_path.open("w", encoding="utf-8") as fh:
        fh.write(_YAML_HEADER)
        yaml.dump(
            config,
            fh,
            default_flow_style=False,
            sort_keys=True,
            allow_unicode=True,
        )

    return config, n_added, n_total


def load_export_yaml(
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> dict[str, dict[str, bool]]:
    """
    Load *yaml_path* and return the config dict.

    Raises
    ------
    FileNotFoundError
        If *yaml_path* does not exist.
    ValueError
        If the file cannot be parsed as a YAML mapping.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"{yaml_path} not found — run `ddd export init` first.")
    with yaml_path.open(encoding="utf-8") as fh:
        loaded = yaml.safe_load(fh)
    if not isinstance(loaded, dict):
        raise ValueError(f"{yaml_path} is not a valid YAML mapping.")
    return {
        source: {field: bool(toggle) for field, toggle in fields.items()}
        for source, fields in loaded.items()
        if isinstance(fields, dict)
    }
