"""
Export configuration management (``ddd_export.yaml``).

YAML structure
--------------

.. code-block:: yaml

    # Optional: human-readable names for task / assignment IDs.
    tasks:
      "862": YouTube Watch History
    assignments:
      "359": What IF - Spanish

    # Per-source, per-table field settings.
    # Each field value is one of:
    #   true          — include the field as-is
    #   false         — exclude the field from exports
    #   "alias_name"  — include and rename to alias_name
    #
    # Fields not mentioned are included as-is (same as true).

    facebook:
      Ads Interests:
        topics_v2.topics_v2: true
        junk_col: false
      Comments:
        comment: true
        dutch_comment: comment    # alias -> 'comment'

Running ``init_export_yaml`` is always safe: it adds newly discovered
fields while leaving all existing settings untouched.
"""

from __future__ import annotations

import re
import sqlite3
import unicodedata
from pathlib import Path
from typing import Any

import yaml

#: Default path for the export configuration file.
DEFAULT_YAML_PATH = Path("ddd_export.yaml")

#: Top-level YAML keys that are not source names.
_RESERVED_KEYS: frozenset[str] = frozenset({"tasks", "assignments"})

_YAML_HEADER = """\
# ddd_export.yaml — export configuration
# Generated by `ddd create-config`. Edit freely; re-run to pick up new fields.
#
# tasks / assignments (optional)
#   Map task or assignment IDs to human-readable names.
#
# Per-source configuration.  Each table block starts with an optional:
#   .alias: canonical_table_name   — rename/merge this table in exports
#
# Per-field settings (remaining keys in a table block):
#   field_name: alias_name    — include, renamed to alias_name
#   field_name: true          — include as-is (original name)
#   field_name: false         — exclude from exports
#
# Fields not mentioned are included as-is.
# New fields added by `ddd create-config` get an auto-generated alias
# (last dot-segment, lowercased, spaces→underscores, ASCII-only).
#
# Example:
#   facebook:
#     Likes And Reactions:
#       .alias: likes_and_reactions
#       timestamp: timestamp
#       ent_name: ent_name
#     Likes And Reactions 1:
#       .alias: likes_and_reactions   # merge with the table above
#       timestamp: timestamp

"""

#: Output columns produced by :func:`export_data`.
EXPORT_COLUMNS: list[str] = [
    "source",
    "table",
    "participant",
    "assignment",
    "task",
    "field",  # canonical / aliased name
    "original_field",  # raw DB field name
    "row_index",
    "value",
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _normalize_alias(name: str) -> str:
    """
    Convert *name* to a clean snake_case ASCII identifier.

    Steps: NFKD-decompose → drop non-ASCII → lowercase →
    replace runs of non-alphanumeric chars with ``_`` →
    strip leading/trailing ``_``.
    """
    nfkd = unicodedata.normalize("NFKD", name)
    ascii_str = nfkd.encode("ascii", "ignore").decode("ascii")
    lower = ascii_str.lower()
    slug = re.sub(r"[^a-z0-9]+", "_", lower)
    return slug.strip("_") or "field"


def _auto_field_alias(field: str) -> str:
    """Auto-alias for a field: normalize the last dot-separated segment."""
    return _normalize_alias(field.rsplit(".", 1)[-1])


def _auto_table_alias(table_name: str) -> str:
    """Auto-alias for a table: normalize the full table name."""
    return _normalize_alias(table_name)


def _parse_table_config(raw: Any) -> dict[str, bool | str]:
    """
    Parse a raw table block into ``{field: true/false/"alias"}``.

    Accepts both the new simple format and old legacy formats gracefully.
    """
    if not isinstance(raw, dict):
        return {}
    result: dict[str, bool | str] = {}
    for field, setting in raw.items():
        if isinstance(setting, bool):
            result[str(field)] = setting
        elif isinstance(setting, str):
            result[str(field)] = setting  # alias
        elif isinstance(setting, list):
            # Old canonical-group format: treat as alias to the key name itself
            result[str(field)] = True
        # ignore other types
    return result


def _parse_source_config(raw: Any) -> dict[str, dict[str, bool | str]]:
    """
    Parse a raw source block: ``{table_name: {field: true/false/"alias"}}``.
    """
    if not isinstance(raw, dict):
        return {}
    result: dict[str, dict[str, bool | str]] = {}
    for table_name, table_cfg in raw.items():
        result[str(table_name)] = _parse_table_config(table_cfg)
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def init_export_yaml(
    con: sqlite3.Connection,
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> tuple[dict, int, int]:
    """
    Create or update *yaml_path* with all (source, table, field) combinations.

    Rules
    -----
    * Existing field settings are preserved.
    * Fields no longer in the DB are pruned.
    * Newly discovered fields are added as ``true``.
    * Sources / tables no longer in the DB are removed.

    Returns
    -------
    tuple
        ``(config, n_added, n_total)``
    """
    existing: dict[str, Any] = {}
    if yaml_path.exists():
        with yaml_path.open(encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh)
            if isinstance(loaded, dict):
                existing = loaded

    # Fetch all (source, table_name, field) from DB.
    db_rows = con.execute(
        """
        SELECT t.source, t.table_name, f.field
        FROM fields f
        JOIN tables t ON t.table_id = f.table_id
        ORDER BY t.source, t.table_name, f.field
        """
    ).fetchall()

    # Build nested DB structure: {source: {table: {field}}}
    db_struct: dict[str, dict[str, set[str]]] = {}
    for row in db_rows:
        src, tbl, fld = row["source"], row["table_name"], row["field"]
        db_struct.setdefault(src, {}).setdefault(tbl, set()).add(fld)

    config: dict[str, Any] = {}

    # Preserve tasks / assignments.
    for key in ("tasks", "assignments"):
        if key in existing and isinstance(existing[key], dict):
            config[key] = {str(k): str(v) for k, v in existing[key].items()}

    # Carry forward existing source sections, prune stale entries.
    n_added = 0
    n_total = 0
    sources_out: dict[str, dict] = {}

    for source in sorted(db_struct):
        db_tables = db_struct[source]
        existing_src = _parse_source_config(existing.get(source, {}))
        out_src: dict[str, dict] = {}

        for table_name in sorted(db_tables):
            db_fields = db_tables[table_name]
            existing_tbl = existing_src.get(table_name, {})

            # .alias is always first; preserve existing or auto-generate.
            out_tbl: dict[str, bool | str] = {}
            if ".alias" in existing_tbl:
                out_tbl[".alias"] = existing_tbl[".alias"]
            else:
                out_tbl[".alias"] = _auto_table_alias(table_name)

            # Prune fields no longer in DB, keep the rest.
            for f, setting in existing_tbl.items():
                if f == ".alias":
                    continue
                if f in db_fields:
                    out_tbl[f] = setting

            # Add newly discovered fields with auto-generated aliases.
            for field in sorted(db_fields):
                if field not in out_tbl:
                    out_tbl[field] = _auto_field_alias(field)
                    n_added += 1

            out_src[table_name] = out_tbl
            n_total += len(out_tbl) - 1  # don't count .alias in field total

        sources_out[source] = out_src

    class _IndentedDumper(yaml.Dumper):
        def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:  # type: ignore[override]
            return super().increase_indent(flow=flow, indentless=False)

    def _dump(obj: Any) -> str:
        return yaml.dump(obj, Dumper=_IndentedDumper, default_flow_style=False, sort_keys=False, allow_unicode=True)

    with yaml_path.open("w", encoding="utf-8") as fh:
        fh.write(_YAML_HEADER)

        reserved = {k: config[k] for k in ("tasks", "assignments") if k in config}
        if reserved:
            fh.write(_dump(reserved))
            fh.write("\n")

        for source, tables in sources_out.items():
            fh.write(_dump({source: tables}))
            fh.write("\n")

    config.update(sources_out)
    return config, n_added, n_total


def load_export_yaml(
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> dict[str, Any]:
    """
    Load *yaml_path* and return a normalised config dict.

    Returns
    -------
    dict with keys:

    ``tasks``
        ``dict[str, str]``

    ``assignments``
        ``dict[str, str]``

    ``sources``
        ``dict[source, dict[table_name, dict[field, bool|str]]]``

    Raises
    ------
    FileNotFoundError
        If *yaml_path* does not exist.
    ValueError
        If the file cannot be parsed as a YAML mapping.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"{yaml_path} not found — run `ddd create-config` first.")
    with yaml_path.open(encoding="utf-8") as fh:
        loaded = yaml.safe_load(fh)
    if not isinstance(loaded, dict):
        raise ValueError(f"{yaml_path} is not a valid YAML mapping.")

    tasks: dict[str, str] = {}
    if "tasks" in loaded and isinstance(loaded["tasks"], dict):
        tasks = {str(k): str(v) for k, v in loaded["tasks"].items()}

    assignments: dict[str, str] = {}
    if "assignments" in loaded and isinstance(loaded["assignments"], dict):
        assignments = {str(k): str(v) for k, v in loaded["assignments"].items()}

    sources: dict[str, dict[str, dict[str, bool | str]]] = {}
    for key, val in loaded.items():
        if key in _RESERVED_KEYS or not isinstance(val, dict):
            continue
        sources[key] = _parse_source_config(val)

    return {"tasks": tasks, "assignments": assignments, "sources": sources}


def build_alias_map(config: dict[str, Any]) -> dict[str, dict[str, dict[str, str]]]:
    """
    Build ``{source: {table_name: {original_field: canonical_field}}}`` from config.

    Only fields with a string alias value are included; ``true`` / ``false``
    fields are not (callers fall back to the original field name for those).
    """
    result: dict[str, dict[str, dict[str, str]]] = {}
    for source, tables in config.get("sources", {}).items():
        for table_name, fields in tables.items():
            for field, setting in fields.items():
                if field == ".alias":
                    continue  # table alias, not a field alias
                if isinstance(setting, str):
                    result.setdefault(source, {}).setdefault(table_name, {})[field] = setting
    return result


def build_table_alias_map(config: dict[str, Any]) -> dict[str, dict[str, str]]:
    """
    Build ``{source: {original_table_name: canonical_table_name}}`` from config.

    Only tables that have a ``.alias`` entry are included; tables without one
    are not present (callers fall back to the original name).
    """
    result: dict[str, dict[str, str]] = {}
    for source, tables in config.get("sources", {}).items():
        for table_name, fields in tables.items():
            alias = fields.get(".alias")
            if isinstance(alias, str):
                result.setdefault(source, {})[table_name] = alias
    return result


def build_exclusion_set(config: dict[str, Any]) -> dict[str, dict[str, frozenset[str]]]:
    """
    Build ``{source: {table_name: frozenset(excluded_fields)}}`` from config.
    """
    result: dict[str, dict[str, frozenset[str]]] = {}
    for source, tables in config.get("sources", {}).items():
        for table_name, fields in tables.items():
            excluded = frozenset(f for f, setting in fields.items() if setting is False)
            if excluded:
                result.setdefault(source, {})[table_name] = excluded
    return result


def export_data(
    con: sqlite3.Connection,
    sources: list[str] | None = None,
    *,
    include_all: bool = False,
    config: dict[str, Any] | None = None,
    assignment: str | None = None,
    task: str | None = None,
) -> tuple[list[str], list[dict[str, str | None]]]:
    """
    Export data rows with alias mapping and exclusion filtering applied.

    Parameters
    ----------
    con:
        Open database connection.
    sources:
        Source names to include. ``None`` / empty = all sources.
    include_all:
        When ``True``, ignore ``.excluded`` (``false``) settings.
    config:
        Pre-loaded config from :func:`load_export_yaml`.
    assignment:
        Optional assignment ID filter.
    task:
        Optional task ID filter.

    Returns
    -------
    tuple
        ``(EXPORT_COLUMNS, rows)``
    """
    if config is None:
        config = {"tasks": {}, "assignments": {}, "sources": {}}

    alias_map = build_alias_map(config)
    table_alias_map = build_table_alias_map(config)
    exclusion_set = {} if include_all else build_exclusion_set(config)

    conditions: list[str] = []
    params: list[Any] = []

    if sources:
        placeholders = ",".join("?" * len(sources))
        conditions.append(f"t.source IN ({placeholders})")
        params.extend(sources)

    if assignment is not None:
        conditions.append("fi.assignment = ?")
        params.append(assignment)

    if task is not None:
        conditions.append("fi.task = ?")
        params.append(task)

    where_clause = ("WHERE " + " AND ".join(conditions)) if conditions else ""

    sql = f"""
        SELECT
            t.source          AS source,
            t.table_name      AS table_name,
            p.participant     AS participant,
            fi.assignment     AS assignment,
            fi.task           AS task,
            f.field           AS original_field,
            d.row_index       AS row_index,
            d.value           AS value
        FROM data d
        JOIN files        fi ON fi.file_id       = d.file_id
        JOIN fields       f  ON f.field_id        = d.field_id
        JOIN tables       t  ON t.table_id        = f.table_id
        JOIN participants p  ON p.participant_id  = fi.participant_id
        {where_clause}
        ORDER BY t.source, t.table_name, p.participant, d.row_index, f.field
    """

    raw_rows = con.execute(sql, params).fetchall()

    rows: list[dict[str, str | None]] = []
    for row in raw_rows:
        src: str = row["source"]
        tbl: str = row["table_name"]
        orig: str = row["original_field"]

        orig_nfc = unicodedata.normalize("NFC", orig)

        # Check exclusion.
        if orig_nfc in exclusion_set.get(src, {}).get(tbl, frozenset()):
            continue

        # Resolve alias.
        canonical: str = alias_map.get(src, {}).get(tbl, {}).get(orig_nfc, orig_nfc)

        canonical_table = table_alias_map.get(src, {}).get(tbl, tbl)
        rows.append(
            {
                "source": src,
                "table": canonical_table,
                "participant": row["participant"],
                "assignment": row["assignment"],
                "task": row["task"],
                "field": canonical,
                "original_field": orig,
                "row_index": str(row["row_index"]),
                "value": row["value"],
            }
        )

    return EXPORT_COLUMNS, rows
