"""
Export configuration management (``ddd_export.yaml``).

YAML structure
--------------

.. code-block:: yaml

    # Optional: give human-readable names to task IDs.
    tasks:
      "10": YouTube Watch History
      "20": Chrome Browsing History

    # Optional: give human-readable names to assignment IDs.
    assignments:
      "1": Pilot Round
      "2": Main Study

    # ── Field settings ──────────────────────────────────────────────────

    # One section per source.
    #
    # Each key is a canonical output name.  The list under it contains all
    # source field names that should be merged into that canonical name.
    # A field listed under its own name is a simple pass-through.
    #
    # Fields under the special ``.excluded`` key are dropped from exports.
    #
    # Fields not mentioned anywhere are included as-is (same as listing
    # them under their own name).

    facebook:
      created:          # canonical output name
        - created       # source field (pass-through)
        - gemaakt       # aliased to 'created'
      .included:
        - title
        - url
      .excluded:
        - feed
        - join requests

Running ``init_export_yaml`` is always safe: it adds newly discovered
fields while leaving all existing settings untouched.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

import yaml

#: Default path for the export configuration file.
DEFAULT_YAML_PATH = Path("ddd_export.yaml")

#: Top-level YAML keys that are not source names.
_RESERVED_KEYS: frozenset[str] = frozenset({"tasks", "assignments"})

#: Special key within a source block listing excluded fields.
_EXCLUDED_KEY = ".excluded"

#: Special key within a source block listing pass-through fields.
_INCLUDED_KEY = ".included"

_YAML_HEADER = """\
# ddd_export.yaml — export configuration
# Generated by `ddd create-config`. Edit freely; re-run to pick up new fields.
#
# tasks (optional)
#   Map task IDs (strings) to human-readable names.
#   tasks:
#     "10": YouTube Watch History
#     "20": Chrome Browsing History
#
# assignments (optional)
#   Map assignment IDs (strings) to human-readable names.
#   assignments:
#     "1": Pilot Round
#     "2": Main Study
#
# Per-source field settings
#   .included  — flat list of fields to include as-is (pass-throughs)
#   .excluded  — flat list of fields to drop from exports
#   Other keys — canonical output name with a list of source fields merged into it
#                (a field under its own name in .included is a pass-through)
#
#   Fields not mentioned anywhere are included as-is (same as .included).
#
#   Example:
#     facebook:
#       created:           <- canonical group (alias/rename)
#         - created
#         - gemaakt
#       .included:
#         - title
#         - url
#       .excluded:
#         - feed
#         - join requests

"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _parse_source_config(raw: Any) -> tuple[dict[str, list[str]], list[str]]:
    """
    Parse a raw source block from the YAML into ``(groups, excluded)``.

    ``groups``
        ``{canonical: [field, ...]}`` — canonical output name → list of
        source fields that map to it.
    ``excluded``
        Flat list of field names to exclude.

    Handles the previous ``{field: bool|str}`` format gracefully by
    treating ``true`` as a pass-through and ``str`` as an alias target.
    """
    if not isinstance(raw, dict):
        return {}, []

    groups: dict[str, list[str]] = {}
    excluded: list[str] = []

    for key, val in raw.items():
        if key == _EXCLUDED_KEY:
            if isinstance(val, list):
                excluded = [str(f) for f in val]
            continue

        if key == _INCLUDED_KEY:
            if isinstance(val, list):
                for item in val:
                    groups[str(item)] = [str(item)]
            continue

        # New list format.
        if isinstance(val, list):
            groups[str(key)] = [str(f) for f in val]
            continue

        # Backward-compat: old bool format → pass-through or exclude.
        if isinstance(val, bool):
            if val:
                groups[str(key)] = [str(key)]
            else:
                excluded.append(str(key))
            continue

        # Backward-compat: old string alias format → alias.
        if isinstance(val, str):
            groups[str(val)] = groups.get(str(val), [])
            groups[str(val)].append(str(key))
            continue

        # Old dict format {include: bool, aliases: [...]}.
        if isinstance(val, dict):
            include = bool(val.get("include", True))
            aliases = [str(a) for a in val.get("aliases", [])]
            if include:
                groups[str(key)] = [str(key)] + aliases
            else:
                excluded.append(str(key))
                excluded.extend(aliases)

    return groups, excluded


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def init_export_yaml(
    con: sqlite3.Connection,
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> tuple[dict, int, int]:
    """
    Create or update *yaml_path* with all (source, field) combinations.

    Rules applied on every run
    --------------------------
    * The ``tasks`` and ``assignments`` blocks are preserved unchanged.
    * Existing canonical groups and ``.excluded`` lists are preserved.
    * Items no longer in the DB are pruned from groups and ``.excluded``.
    * Canonical groups whose item lists become empty are removed.
    * Newly discovered fields are added as a pass-through group
      ``field: [field]``.
    * A field already covered (in any group or ``.excluded``) is not
      added again.
    * Sources no longer in the DB are removed.

    Returns
    -------
    tuple
        ``(config, n_added, n_total)`` where *n_added* is the number of
        new pass-through groups created and *n_total* is the total number
        of distinct field entries across all sources.
    """
    existing: dict[str, Any] = {}
    if yaml_path.exists():
        with yaml_path.open(encoding="utf-8") as fh:
            loaded = yaml.safe_load(fh)
            if isinstance(loaded, dict):
                existing = loaded

    db_rows = con.execute("SELECT source, field FROM fields ORDER BY source, field").fetchall()
    db_sources: set[str] = {row["source"] for row in db_rows}
    db_fields_by_source: dict[str, set[str]] = {}
    for row in db_rows:
        db_fields_by_source.setdefault(row["source"], set()).add(row["field"])

    config: dict[str, Any] = {}

    if "tasks" in existing and isinstance(existing["tasks"], dict):
        config["tasks"] = {str(k): str(v) for k, v in existing["tasks"].items()}

    if "assignments" in existing and isinstance(existing["assignments"], dict):
        config["assignments"] = {str(k): str(v) for k, v in existing["assignments"].items()}

    # Carry forward existing source sections.
    carried: dict[str, tuple[dict[str, list[str]], list[str]]] = {}
    for key, val in existing.items():
        if key in _RESERVED_KEYS or not isinstance(val, dict):
            continue
        if key not in db_sources:
            continue
        db_fields = db_fields_by_source.get(key, set())
        groups, excluded = _parse_source_config(val)

        # Prune items no longer in DB; drop groups that become empty.
        pruned_groups = {canonical: [f for f in fields if f in db_fields] for canonical, fields in groups.items()}
        pruned_groups = {c: fs for c, fs in pruned_groups.items() if fs}
        pruned_excluded = [f for f in excluded if f in db_fields]

        carried[key] = (pruned_groups, pruned_excluded)

    # Add newly discovered fields.
    n_added = 0
    for source in sorted(db_fields_by_source):
        db_fields = db_fields_by_source[source]
        groups, excluded = carried.get(source, ({}, []))

        # Fields already accounted for (in any group or excluded).
        covered: set[str] = {f for fs in groups.values() for f in fs} | set(excluded)

        for field in sorted(db_fields):
            if field not in covered:
                groups[field] = [field]
                n_added += 1

        carried[source] = (groups, excluded)

    # Write sources in sorted order, .included then .excluded last within a source.
    n_total = 0
    sources_out: dict[str, dict] = {}
    for source in sorted(carried):
        groups, excluded = carried[source]

        # Separate pass-throughs from canonical groups (real aliases/renames).
        pass_throughs: list[str] = []
        canonical_groups: dict[str, list[str]] = {}
        for canonical, items in groups.items():
            if len(items) == 1 and items[0] == canonical:
                pass_throughs.append(canonical)
            else:
                canonical_groups[canonical] = items

        # Build block: canonical groups first, then .included, then .excluded.
        block: dict[str, Any] = dict(sorted(canonical_groups.items()))
        if pass_throughs:
            block[_INCLUDED_KEY] = sorted(pass_throughs)
        if excluded:
            block[_EXCLUDED_KEY] = sorted(excluded)
        sources_out[source] = block
        n_total += sum(len(fs) for fs in groups.values()) + len(excluded)

    def _dump(obj: Any) -> str:
        class _IndentedDumper(yaml.Dumper):
            """Dumper that indents block-sequence items under their key."""

            def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:  # type: ignore[override]
                return super().increase_indent(flow=flow, indentless=False)

        return yaml.dump(obj, Dumper=_IndentedDumper, default_flow_style=False, sort_keys=False, allow_unicode=True)

    with yaml_path.open("w", encoding="utf-8") as fh:
        fh.write(_YAML_HEADER)

        reserved = {k: config[k] for k in ("tasks", "assignments") if k in config}
        if reserved:
            fh.write(_dump(reserved))
            fh.write("\n")

        fh.write(
            "# \u2500\u2500 Field settings \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n\n"
        )
        for source, block in sources_out.items():
            fh.write(_dump({source: block}))
            fh.write("\n")

    config.update(sources_out)
    return config, n_added, n_total


def load_export_yaml(
    yaml_path: Path = DEFAULT_YAML_PATH,
) -> dict[str, Any]:
    """
    Load *yaml_path* and return a normalised config dict.

    The returned dict has three top-level keys:

    ``tasks``
        ``dict[str, str]`` mapping task IDs to human-readable names.

    ``assignments``
        ``dict[str, str]`` mapping assignment IDs to human-readable names.

    ``sources``
        ``dict[str, dict]`` — per-source parsed config, each containing:

        * ``"groups"``   — ``{canonical: [field, ...]}``
        * ``"excluded"`` — ``[field, ...]``

    Raises
    ------
    FileNotFoundError
        If *yaml_path* does not exist.
    ValueError
        If the file cannot be parsed as a YAML mapping.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"{yaml_path} not found — run `ddd create-config` first.")
    with yaml_path.open(encoding="utf-8") as fh:
        loaded = yaml.safe_load(fh)
    if not isinstance(loaded, dict):
        raise ValueError(f"{yaml_path} is not a valid YAML mapping.")

    tasks: dict[str, str] = {}
    if "tasks" in loaded and isinstance(loaded["tasks"], dict):
        tasks = {str(k): str(v) for k, v in loaded["tasks"].items()}

    assignments: dict[str, str] = {}
    if "assignments" in loaded and isinstance(loaded["assignments"], dict):
        assignments = {str(k): str(v) for k, v in loaded["assignments"].items()}

    sources: dict[str, dict] = {}
    for key, val in loaded.items():
        if key in _RESERVED_KEYS or not isinstance(val, dict):
            continue
        groups, excluded = _parse_source_config(val)
        sources[key] = {"groups": groups, "excluded": excluded}

    return {"tasks": tasks, "assignments": assignments, "sources": sources}


def build_alias_map(config: dict[str, Any]) -> dict[str, dict[str, str]]:
    """
    Build a per-source ``{field: canonical}`` lookup from a loaded config.

    Every field that appears in a canonical group is mapped to that
    group's name.  Fields not mentioned (implicit pass-throughs) are not
    in the map — callers should fall back to the field's own name.

    Example
    -------
    Given::

        facebook:
          created:
            - created
            - gemaakt

    The result is ``{"facebook": {"created": "created", "gemaakt": "created"}}``.
    """
    alias_map: dict[str, dict[str, str]] = {}
    for source, src_cfg in config.get("sources", {}).items():
        mapping: dict[str, str] = {}
        for canonical, fields in src_cfg.get("groups", {}).items():
            for field in fields:
                mapping[field] = canonical
        if mapping:
            alias_map[source] = mapping
    return alias_map


def build_exclusion_set(config: dict[str, Any]) -> dict[str, frozenset[str]]:
    """
    Build a per-source set of excluded field names from a loaded config.

    Returns
    -------
    dict
        ``{source: frozenset[field]}`` — only sources with at least one
        excluded field are included.
    """
    return {
        source: frozenset(src_cfg["excluded"])
        for source, src_cfg in config.get("sources", {}).items()
        if src_cfg.get("excluded")
    }
